services:
    mssqlserver-container:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - "1433:1433"
        volumes:
            - userauth-data:/var/opt/mssql
        environment:
            MSSQL_SA_PASSWORD: "c#connection24"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        restart: always
    
    userauth-container:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - mssqlserver-container
        environment:
            ConnectionStrings__UserAuthContext: "Server=mssqlserver-container,1433;Database=UserAuthDB;User ID=sa;Password=c#connection24;TrustServerCertificate=True;Trusted_Connection=False;MultipleActiveResultSets=True;"
        restart: always

volumes:
    userauth-data:
        driver: local